name: "Snyk scan"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - name: Snyk
      uses: snyk/actions@0.3.0
